# Generated by Django 4.0.1 on 2023-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('books_cbv', '0001_initial'),
  ]

  operations = [
    migrations.AlterField(
      model_name='book',
      name='pages',
      field=models.PositiveIntegerField(),
    ),
  ]